#cloud-config

packages:
  - docker.io
  
# create the docker group
groups:
  - docker
  
users:
  - name: ubuntu
    groups: docker
    home: /home/ubuntu
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh-authorized-keys:
      - ${ssh_public_key}

# Add default auto created user to docker group
system_info:
  default_user:
    groups: [docker]

# https://docs.docker.com/engine/reference/commandline/login/
runcmd:
  - docker login ${docker_registry} --username=${docker_registry_user} --password=${docker_registry_password}
  - docker pull ${docker_image_name}
  - docker run --restart=always -p=80:80 -e "SWAPS_DB_HOST=${swaps_database_host}" -e "SWAPS_DB_DATABASE=${swaps_database_name}" -e "SWAPS_DB_USER=${swaps_database_username}" -e "SWAPS_DB_PASSWORD=${swaps_database_password}" -e "SWAPS_DB_PORT=${swaps_database_port}" -e "FOOD_DB_DB_HOST=${food_database_host}" -e "FOOD_DB_DATABASE=${food_database_name}" -e "FOOD_DB_USER=${food_database_username}" -e "FOOD_DB_PASSWORD=${food_database_password}" -e "FOOD_DB_PORT=${food_database_port}" -e "X_AUTH_TOKEN=${swaps_api_auth_token}" -e "AWS_EC2_KEY=${iam_ec2_key}" -e "AWS_EC2_SECRET=${iam_ec2_secret}" -e "COMPUTE_INSTANCE_ID=${compute_instance_id}" -e "EC2_REGION=eu-west-2" ${docker_image_name}
